# Workshop: pandas, continued

### Wednesday, March 13, 2022

In today's workshop we'll continue working with `pandas`, turning our attention to the matter of actually using it to clean, explore, summarize and analyze data.

In [1]:
import pandas as pd

## Problem 1: data summaries

Let's grab a larger data set to work with.
Here's the baseball data set from the lecture videos.
Note that this is <b>NOT</b> the same as the baseball data that will be used in your homework!

<a href='http://pages.stat.wisc.edu/~kdlevin/teaching/Spring2024/STAT606/democode/baseball.csv'>Baseball data</a>

### 1.1
Download that data file and read it into a `pandas` DataFrame object sabed in a variable called `baseball`.

<b>Hint:</b> you may find the `read_csv` documentation useful: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

In [2]:
# TODO: code goes here

In [3]:
type(baseball) # Should evaluate to pandas.core.frame.DataFrame once you update above.

pandas.core.frame.DataFrame

### 1.2

Use the `info` method to get an overview of this data set.
Unless you are well-versed in <a href='https://en.wikipedia.org/wiki/Sabermetrics'>sabermetrics</a>, many of the column names are going to be a bit hard to parse.
Don't worry about that.
Instead, make sure you understand what `pandas` is telling you about each of the columns of the data set.
You may find it useful to read the documentation for the `info` method: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html

In [2]:
# TODO: code goes here

### 1.3

Now use the `head` method to look at the first few columns of the data set.
Depending on your display settings, Jupyter notebook may automatically suppress some columns.

In [3]:
# TODO: code goes here

### 1.4
Use the `describe` method to get a summary of the `baseball` data set.
Once again, the fact that this data set has a large number of columns may cause some slightly weird behavior.

In [4]:
#TODO: code goes here

### 1.5

What are the earliest and latest years in the data set (i.e., in the `year` column)?

In [5]:
# TODO: answer here

### 1.6

What is the mean number of at-bats over all players and seasons (the `ab` column)? What about the median?

In [6]:
# TODO: answer here

## Problem 2: Aggregation

Let's continue with the same baseball data set from above.
<b>Reminder:</b> this is <b>NOT</b> the same as the baseball data that is going to be used in your homework!

<a href='http://pages.stat.wisc.edu/~kdlevin/teaching/Spring2023/STAT606/democode/baseball.csv'>Baseball data</a>

### 2.1
If you didn't do Problem 1 above download that data file and read it into a `pandas` DataFrame object, stored in a variable called `baseball`.

In [11]:
# To verify, you can uncomment and run the next line
# baseball.head()

,id,year,stint,team,lg,g,ab,r,h,X2b,...,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,gidp
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
44,forceda01,1871,1,WS3,NaN,32,162,45,45,9,...,29.0,8.0,0.0,4,0.0,NaN,NaN,NaN,NaN,NaN
68,mathebo01,1871,1,FW1,NaN,19,89,15,24,3,...,10.0,2.0,1.0,2,0.0,NaN,NaN,NaN,NaN,NaN
99,startjo01,1871,1,NY2,NaN,33,161,35,58,5,...,34.0,4.0,2.0,3,0.0,NaN,NaN,NaN,NaN,NaN
102,suttoez01,1871,1,CL1,NaN,29,128,35,45,3,...,23.0,3.0,1.0,1,0.0,NaN,NaN,NaN,NaN,NaN

### 2.2

Use a group-by operation to determine the mean number of RBIs (these are essentiall analogous to the number of points scored by a player) by all players within each year.

Group-by documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

Possibly also useful, the `aggregate` method: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.SeriesGroupBy.aggregate.html

In [7]:
#TODO: code goes here

### 2.3

Plot the mean number of RBIs as a function of year. Do you see any trends?

<b>Hint:</b> See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html and note that `GroupBy` objects also support a similar method (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.plot.html)

<b>Note:</b> a thing that always trips me up is that the `x` keyword argument to `plot` is implicitly already set when you call the `plot` method for a `GroupBy` object. In particular, if you've grouped by `year` already, the `x` argument is implicitly set to `year` already, and trying to set it explicitly will result in an error.

In [8]:
# TODO: code goes here

### 2.4

Compute the year-by-year percentage changes in the RBI sequence and plot it also as a function of time.

In [9]:
# TODO: code goes here

### 2.5

Plot those changes as a function of time. Do you see any trends?

In [10]:
# TODO: code goes here

### 2.6

Write code to compute the mean, median, min and max of the number of home runs (the `hr` column) in the 1997 season (i.e., `year=1997`).

In [11]:
#TODO: code goes here

## Problem 3: pivoting, stacking and aggregation

Here is some stacked data. Pivot it so that we have a new table with `V1` as the columns and `V2` as the rows.

<b>Hint:</b> documentation related to pivoting and stacking are here:
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unstack.html

In [30]:
df = pd.DataFrame({'V1':3*['A']+3*['B']+3*['C'],
                  'V2':[1,2,3,1,2,3,1,2,3],
                  'value':[1,2,3,4,5,6,7,8,9]})
df

  V1  V2  value
0  A   1      1
1  A   2      2
2  A   3      3
3  B   1      4
4  B   2      5
5  B   3      6
6  C   1      7
7  C   2      8
8  C   3      9

In [12]:
#TODO: code goes here

In [70]:
# Observe that stacking pvt recovers our original data frame,
# albeit with the V1 and V2 columns now stored as a hierarchical row index.
pd.DataFrame( pvt.stack(), columns=['value'] )

       value
V2 V1
1  A       1
   B       4
   C       7
2  A       2
   B       5
   C       8
3  A       3
   B       6
   C       9

### 3.2

Now, use an aggregation operation to compute the mean within the V1 levels 'A', 'B' and 'C'.

In [13]:
# TODO: code goes here

### 3.3
Do the same thing, this time within the V2 levels 1, 2 and 3.

In [15]:
# TODO: code goes here

## Problem 4: More pivoting

### 4.1
Create a table with four rows, and a depth-three hierarchical structure, corresponding to all combinations of the conditions `animal` (two levels: `llama` and `goat`), `color` (three levels: `white`, `brown` and `black`), and `feed` (two levels: `grass` and `grains`).
Your table should have five rows, with entries populated by independent standard normals.

<b> Before diving in:</b> think about how this table should look (perhaps even draw it out) before you try and create it in `pandas`!

In [16]:
#TODO: code goes here

### 4.2

Now, write code to stack (i.e., unpivot) this table.

<b>Before proceeding:</b> discuss what this table should look like after this operation. Again, perhaps try drawing it out before actually writing any code, to make sure you understand the operation.

In [17]:
# TODO: code goes here